config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users, only:[:sign_in, :sign_out, :session]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#top"
  get "home/bio" => "homes#bio"
  resources :categories, param: :name, only:[:index, :create, :show]
  resources :musics do
    resources :music_choices, expect: [:new, :show]
    get '/previews' => 'music_choices#previews'
  end
   resources :news
   resources :top_musics, only:[:create, :destroy]
   get 'news/search' => 'news/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true
  has_many :musics
  
  def to_param
    name
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :category
  validates :image, presence: true
  attachment :image
  has_many :music_choices, dependent: :destroy
  has_many :news_musics, dependent: :destroy
  has_many :news, through: :news_musics
  has_many :top_musics, dependent: :destroy
end

app/models/music_choice.rb
class MusicChoice < ApplicationRecord
  validates :lyrics, presence: true
  validates :song_title, presence: true
  belongs_to :music
  attachment :background_image
end

app/models/news.rb
class News < ApplicationRecord
  attachment :news_image
  has_many :news_musics, dependent: :destroy
  has_many :musics, through: :news_musics
end

app/models/news_music.rb
class NewsMusic < ApplicationRecord
  belongs_to :news
  belongs_to :music
end

app/models/top_music.rb
class TopMusic < ApplicationRecord
  belongs_to :music
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
    @top_music = TopMusic.new
  end

  def create
   category = Category.new(category_params)
   category.save
   redirect_to categories_path
  end

  def show
   category = Category.find_by(name: params[:name])
   @categories = Category.all
   @musics = category.musics
  end
private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver_now
      redirect_to contacts_path, notice: 'メールが送信されました。'
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @top_musics = TopMusic.order(updated_at: :desc).limit(1)
    @news = News.last(3)
  end

  def bio
  end
end

app/controllers/music_choices_controller.rb
class MusicChoicesController < ApplicationController

  def index
    music = Music.find(params[:music_id])
    @music_choices = music.music_choices.order(created_at: :asc)
  end

  def previews
    music = Music.find(params[:music_id])
    @music_choices = music.music_choices
  end

  def create
    music = Music.find(params[:music_id])
    music_choice = music.music_choices.build(choice_params)
    music_choice.save
    redirect_to music_path(music.id)
  end

  def edit
    @music = Music.find(params[:music_id])
    @music_choice = MusicChoice.find(params[:id])
  end

  def update
    music = Music.find(params[:music_id])
    music_choice = MusicChoice.find(params[:id])
    music_choice.update(choice_params)
    redirect_to music_music_choices_path(music.id)
  end

  def destroy
    choice = MusicChoice.find_by(id: params[:id], music_id: params[:music_id])
    choice.destroy
    redirect_to  music_music_choices_path(params[:music_id])
  end
  


private
  def choice_params
    params.require(:music_choice).permit(:lyrics, :song_title, :commentary, :background_image, :sound_cloud, :color)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def new
    @music = Music.new
    @musics = Music.all
  end

  def create
    @music = Music.new(music_params)
    if @music.save
      redirect_to new_music_path
    else
      @musics = Music.all
      render :new
    end
  end

  def index
  @musics = Music.all
  @categories = Category.all
  end
  
  def show
    @music =Music.find(params[:id])
    @music_choice = MusicChoice.new
    @music_choices = @music.music_choices
  end
 
private

  def music_params
    params.require(:music).permit(:category_id, :image, :title, :price, :release, :presave)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news= News.new
  end
  
  def create
    news = News.create(title: news_params[:title], body: news_params[:body], news_image: news_params[:news_image])
    
    if news_params[:music_id].present?
      music = Music.find_by(id: news_params[:music_id])
      NewsMusic.create(news_id: news.id, music_id: music.id)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def index
    @news = News.all.order(id: "DESC")
  end

  def show
    @news = News.find(params[:id])
    @news_music = NewsMusic.find_by(news_id: @news.id)
  end
  private
  def news_params
    params.require(:news).permit(:title, :body, :news_image, :music_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/music_choices_helper.rb
module MusicChoicesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/top_musics_helper.rb
module TopMusicsHelper
end

app/views/music_choices/_choice.html.erb
   <div class="container">
    <div class="row"> 
     <div class="col-12 mx-auto">
    <%= form_with(model: [music, music_choice], local: true) do |f| %>
    
    <div class="field">
    <%= f.label "曲名" %>
    <%= f.text_field :song_title, class:"form-control"%>
    </div>

   <div class="field">
    <%= f.label "歌詞" %>
    <%= f.text_area :lyrics, class:"form-control" %>
   </div>
   
   <div class="field">
    <%= f.label "歌詞色"%>
    <%= f.color_field :color %>
   </div>
   
   <div class="field">
    <%= f.label "解説"%>
    <%= f.text_area :commentary, class:"form-control" %>
   </div>
   <div class="field">
    <%= f.label "背景画像"%>
    <%= f.attachment_field :background_image %>
   </div>
   
   <div class="field">
    <%= f.label "サンクラ"%>
    <%= f.text_field :sound_cloud, class:"form-control" %>
   </div>
    <%= f.submit "作成", class:"btn btn-info"%>
    <% end %>
    </div>
   </div>
  </div>

app/views/music_choices/edit.html.erb
<%= render "music_choices/choice", music: @music, music_choice: @music_choice %>

app/views/music_choices/index.html.erb
<div id="global-container">
  <h1>プレビュー</h1>
  <div class="main-image">
    <%#= image_tag asset_path("main.jpg", alt: "butohes"), class:"main-image-b" %>
    <div class="main-image-b"></div>
     <span class="main-title animate__animated animate__fadeInUp">　Lost in Water cycle</span>
     <span class="main-title2 animate__animated animate__fadeInUp">First EP</span>
   　<div class="main-footer">
      <%= image_tag asset_path("arrow.svg"), class:"down-arrow" %>
     <span class="main-text">scroll</span>
    </div>
  </div>
  <%# <aside class="side left">
    <div class="side_inner animate__animated animate__fadeInLeft">
    <a class="twitter icon" href="#">Twitter</a>
    <a class="instagram icon" href="#">Instagram</a>
    </div>
  </aside> %>
  <% @music_choices.each do |choice| %>
    <div class="back-image">
      <%= attachment_image_tag choice, :background_image, class:"choice-image", format: 'png' %>
        <div class="lyrics float" style="color: <%= choice.color %>">
          <div data-iziModal-open=".iziModal_<%= choice.id %>">
          <%= simple_format(choice.lyrics) %>
          </div>
        </div>
        <div class="iziModal_<%= choice.id %>" data-izimodal-title="解説" data-izimodal-subtitle="解説者">
            <div class="commentary">
              <%= simple_format(choice.commentary)%>
            </div>
        </div>
         <%= choice.sound_cloud.to_s.html_safe %>
      <span class="title" style="color: <%= choice.color %>;">
      　<%= choice.song_title %>
      </span>
    </div>

      <%= link_to "削除", music_music_choice_path(choice.music, choice), method: :delete, local: true %>
      <%= link_to "戻る", music_path(choice.music), class:"btn btn-info" %>
      <%= link_to "編集", edit_music_music_choice_path(choice.music, choice) %>

  <script type="text/javascript">
  $(function(){
    $(".iziModal_<%= choice.id %>").iziModal();
  })
  </script>
  <% end %>
   <%# <aside class="side right">
    <div class="side_inner">
    <span>©︎butohes</span>
    </div>
  </aside> %>
  <%= link_to "総合プレビュー",  music_previews_path, "data-turbolinks" => "false" %>
</div>
<div class="text-test">
  <div class="lyrics" style="color: white;">
    <p> <br>まぶたを下ろして眼を開けると、無辺際の空間に立っていた。<br>
    目の前、ぼんやりと自分の影が映っている。果てが見えない、大きなガラスだった。<br>
  <br>
  　ガラスの向こうを注視すると、泡が見えたが止まっている。<br>
    なぜかそれを個体に入った気泡だとは認識しなかった。<br>
    向こうにあるのは、水だと、どこかで知っていたようだ。<br>
  <br>
  　ふりかえると、無数の小さな水槽が嵌め込まれている。<br>
    水族館とおなじように、そのひとつひとつに魚の名前と解説文を載せるためのプレートが添えてあった。<br>
    しかし、そこに何が書かれているのかは読み取れない。<br>
  <br>
  　歩きながら中を覗く。けれど、どれも中には、水があるだけだった。<br>
  <br>
  　いくら歩いても出口はなく、一本道。奥行きは認められず、これといった変化もない。何時間も過ぎたころに、その水槽の中に細切れの錯覚が見えはじめる。
  </p>
  </div>
  <div class="lyrics" style="color: white;">
    三角形の陽だまり／足に落ちた波の影　エンドロール／豪雨の音／骨だけになった傘に絡まる蔦／半分になったデススターのようなオブジェ／指先／<br>
    impression, soleil levant／深海魚の標本／誰かの髪/消え入りそうな白い声音<br>
    <br>
  　ふと、ガラスに手を添えた。コツ、と音がする。手のひらをみると、亀裂が入っていた。隙間から、水が流れ出す。<br>
    こぼれることがおそろしいことだと思って、もう片方の手で抑えようとするけれど、うまくいかない。<br>
  <br>
  　狼狽えているうちに全身が震えはじめる。いや、震えているのはこの空間そのものだった。<br>
    無数のガラスにも、大きなガラスにも、罅が入る。亀裂の奥に水泡が、いくつも流れていく。ただし、上から下へ。無数の線と無数の球。<br>
    なにかの譜面のようだ。<br>
  <br>
  　なんとか走り出そうとする。向かう先はわからない。
    光が見えた気がしたほうへ、よろめきながら走り出す、その一歩めで、決壊した。<br>
  　すぐに溺れた。すべてが雪崩れこんでくる。なかったことにしたかった、裏返しておいた、あらゆるシーンが。どこかへ向かって落ちていく。<br>
    <br>
    <br>
    <br>
  　体がなくなった<br>
  <br>
  　遠くで、誰かが、光の言葉を話した
  </div>
</div>
<%= javascript_include_tag 'iziModal.min.js' %>
<script>
$(window).on("load", function(){
 $("div").removeClass("global-container");
});
</script>

app/views/music_choices/previews.html.erb
<div id="global-container" style="background-color: #000044;">
  <div class="main-image">
     <div class="main-image-b"></div>
     <span class="main-title animate__animated animate__fadeInUp">Lost in Watercycle</span>
     <span class="main-title2 animate__animated animate__fadeInUp">First EP</span>
   　<div class="main-footer">
      <%= image_tag asset_path("arrow.svg"), class:"down-arrow" %>
     <span class="main-text">scroll</span>
    </div>
  </div>
   <%# <aside class="side left">
    <div class="side_inner">
        <a class="twitter icon" href="#">Twitter</a>
        <a class="instagram icon" href="#">Instagram</a>
    </div>
  </aside> %>
  <% @music_choices.each do |choice| %>
    <div id="image-songs"class="back-image">
      <%= attachment_image_tag choice, :background_image, class:"choice-image", format: 'png' %>
        <div class="lyrics float" style="color: <%= choice.color %>">
          <div data-iziModal-open=".iziModal_<%= choice.id %>">
          <%= simple_format(choice.lyrics) %>
          </div>
        </div>
        <div class="iziModal_<%= choice.id %>" data-izimodal-title="解説" data-izimodal-subtitle="解説者">
            <div class="commentary">
              <%= simple_format(choice.commentary)%>
            </div>
        </div>
         <%= choice.sound_cloud.to_s.html_safe %>
      <span class="title" style="color: <%= choice.color %>;">
      　<%= choice.song_title %>
      </span>
    </div>

  <script type="text/javascript">
  $(function(){
    $(".iziModal_<%= choice.id %>").iziModal();
  })
  </script>

  <% end %>
   <%# <aside class="side right">
    <div class="side_inner">
    <span>©︎butohes</span>
    </div>
  </aside> %>
  </div>
<%= javascript_include_tag 'TweenMax.min.js' %>
<%= javascript_include_tag 'music_choices.js' %>
<%= javascript_include_tag 'iziModal.min.js' %>
<%= javascript_include_tag 'jquery.ripples-min.js' %>