config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users, only:[:sign_in, :sign_out, :session]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#top"
  get "home/bio" => "homes#bio"
  resources :categories, param: :name, only:[:index, :create, :show]
  resources :musics do
    resources :music_choices, expect: [:new, :show]
    get '/previews' => 'music_choices#previews'
  end
   resources :news
   resources :top_musics, only:[:create, :destroy]
   get 'news/search' => 'news/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true
  has_many :musics
  
  def to_param
    name
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :category
  validates :image, presence: true
  attachment :image
  has_many :music_choices, dependent: :destroy
  has_many :news_musics, dependent: :destroy
  has_many :news, through: :news_musics
  has_many :top_musics, dependent: :destroy
end

app/models/music_choice.rb
class MusicChoice < ApplicationRecord
  validates :lyrics, presence: true
  validates :song_title, presence: true
  belongs_to :music
  attachment :background_image
end

app/models/news.rb
class News < ApplicationRecord
  attachment :news_image
  has_many :news_musics, dependent: :destroy
  has_many :musics, through: :news_musics
end

app/models/news_music.rb
class NewsMusic < ApplicationRecord
  belongs_to :news
  belongs_to :music
end

app/models/top_music.rb
class TopMusic < ApplicationRecord
  belongs_to :music
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
    @top_music = TopMusic.new
  end

  def create
   category = Category.new(category_params)
   category.save
   redirect_to categories_path
  end

  def show
   category = Category.find_by(name: params[:name])
   @categories = Category.all
   @musics = category.musics
  end
private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver_now
      redirect_to contacts_path, notice: 'メールが送信されました。'
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @top_musics = TopMusic.order(updated_at: :desc).limit(1)
    @news = News.last(3)
  end

  def bio
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def new
    @music = Music.new
    @musics = Music.all
  end

  def create
    @music = Music.new(music_params)
    if @music.save
      redirect_to new_music_path
    else
      @musics = Music.all
      render :new
    end
  end

  def index
  @musics = Music.all
  @categories = Category.all
  end
  
  def show
    @music =Music.find(params[:id])
    @music_choice = MusicChoice.new
    @music_choices = @music.music_choices
  end
 
private

  def music_params
    params.require(:music).permit(:category_id, :image, :title, :price, :release, :presave)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news= News.new
  end
  
  def create
    news = News.create(title: news_params[:title], body: news_params[:body], news_image: news_params[:news_image])
    
    if news_params[:music_id].present?
      music = Music.find_by(id: news_params[:music_id])
      NewsMusic.create(news_id: news.id, music_id: music.id)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def index
    @news = News.all.order(id: "DESC")
  end

  def show
    @news = News.find(params[:id])
    @news_music = NewsMusic.find_by(news_id: @news.id)
  end
  private
  def news_params
    params.require(:news).permit(:title, :body, :news_image, :music_id)
  end
end

app/controllers/top_musics_controller.rb
class TopMusicsController < ApplicationController
  def create
    top_music = TopMusic.new(top_music_params)
    binding.pry
    top_music.save
    redirect_to root_path
  end

  private
  def top_music_params
    params.require(:top_music).permit(:music_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/music_choices_helper.rb
module MusicChoicesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/top_musics_helper.rb
module TopMusicsHelper
end

app/views/categories/index.html.erb
<%= form_with model:@category, local:true do |f| %>
<%= f.label "カテゴリー"%>
<%= f.text_field :name, class:"form-control"%>
<%= f.submit "追加" %>
<% end %>

<% @categories.each do |category|%>
<%= category.name %>
<% end %>
<p>TOP MUSIC</p>
<%= form_with model: @top_music, local:true do |f| %>
   <div class="category">
     <%= f.collection_select(:music_id, Music.all, :id, :title, prompt: "-- 選択してください--") %>
   </div>
  <%= f.submit '反映' %>
<% end %>

app/views/categories/show.html.erb
<main>
 <div class="container">
  <div class="row">
      <div class="col-lg-2">
      <span class="index-title">MUSIC</span>
      <% @categories.each do | category| %>
       <%= link_to category_path(name: category.name), class:"animsition-link", data: {"turbolinks" => false} do %>
         <span class="categories-name"><%= category.name %></span>
       <% end %>
      <% end %>
      </div>
      <div class="col-lg-10">
          <div class="row">
            <% @musics.each do |music| %>
              <div class="col-lg-4 col-md-6">
                  <%= link_to music_path(music.id), data: {"turbolinks" => false} do %>
                    <div class="music-jk">
                      <%= attachment_image_tag music, :image, format: 'png', fallback: "news.jpg", class:"index-music" %>
                      <div class="mask1"></div>
                      <div class="mask2"></div>
                      <div class="caption">
                        <p>MORE</p>
                      </div>
                    </div>
                  <% end %>
              </div>
            <% end %>
          </div>
      </div>
  </div>
 </div>
</main>
<%= javascript_include_tag "musics.js"%>
<%= javascript_include_tag 'aimsition.js' %>

app/views/contacts/_form.html.erb
<section class="contact">
  <%= form_with(model: contact, local: true, class:"contact-form roo") do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field col x-50">
      <%= form.text_field :name, class:"input-text js-input" %>
      <label class="label" for="name">Name</label>
    </div>

    <div class="form-field col x-50">
      <%= form.text_field :email, class:"input-text js-input" %>
      <label class="label" for="email">E-mail</label>
    </div>

    <div class="form-field col x-100">
      <%= form.text_area :content, class:"input-body js-input" %>
      <label class="label-right" for="message">Message</label>
    </div>

    <div class="form-field col x-100 align-center">
      <%= form.submit "SEND", class:"submit-btn" %>
    </div>
  <% end %>
</section>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
 <main>
    <h1 class="contact_title">Contact</h1>

    <%= render 'form', contact: @contact %>

    <%= javascript_include_tag 'contacts.js' %>
    <%= javascript_include_tag 'aimsition.js' %>
</main>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/musics/index.html.erb
<main>
 <div class="container">
  <div class="row">
      <div class="col-lg-2">
      <span class="index-title">MUSIC</span>
      <% @categories.each do | category| %>
       <%= link_to category_path(name: category.name), class:"animsition-link", data: {"turbolinks" => false} do %>
         <span class="categories-name"><%= category.name %></span>
       <% end %>
      <% end %>
      </div>
      <div class="col-lg-10">
          <div class="row">
            <% @musics.each do |music| %>
              <div class="col-lg-4 col-md-6">
                  <%= link_to music_path(music.id), data: {"turbolinks" => false} do %>
                    <div class="music-jk">
                      <%= attachment_image_tag music, :image, format: 'png', fallback: "news.jpg", class:"index-music" %>
                      <div class="mask1"></div>
                      <div class="mask2"></div>
                      <div class="caption">
                        <p>MORE</p>
                      </div>
                    </div>
                  <% end %>
              </div>
            <% end %>
          </div>
      </div>
  </div>
 </div>
</main>
<%= javascript_include_tag "musics.js"%>
<%= javascript_include_tag 'aimsition.js' %>

app/views/musics/new.html.erb
<h1>ミュージックの作成</h1>
<div class="container">
 <div class="row">
 <div class="col-lg-12">
  <%= form_with model: @music, local:true do |f| %>
  <%= f.label "ジャケット画像" %>
  <%= f.attachment_field :image, class:"music-image" %>

    <%= f.label "タイトル" %>
    <%= f.text_field :title, class:"form-control"%>
          
         
           <%= f.label :"カテゴリー" %>
           <div class="category">
            <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "-- 選択してください--") %>
          </div>

          <%= f.label "リリース日"%>
          <%= f.text_field :release, class:"form-control"%>
          
          <%= f.label "プリセーブ値段"%>
          <%= f.text_field :price, class:"form-control" %>
          
          <%= f.label "プリセーブURL"%>
          <%= f.text_field :presave, class:"form-control"%>
    <div class="music-button">    
    <%= f.submit "作成", class:"btn btn-success mt-auto" %>
    </div>

  <% end %>
  </div>
 </div>
</div>
<% @musics.each do |music| %>
  <%= link_to music_path(music.id) do %>
  <%= attachment_image_tag music, :image, format: 'png', size: "286x180" %>
  <% end %>
<% end %>

app/views/musics/show.html.erb
<% if user_signed_in? %>
  <%= render "music_choices/choice", music: @music, music_choice: @music_choice %>

  <% @music_choices.each do |choice| %>
  <%= choice.song_title %>
  <%= attachment_image_tag choice, :background_image, format: 'png', size: "100x100" %>
  <% end %>

  <%= link_to "プレビューをみる",music_music_choices_path(@music.id), data: {"turbolinks" => false} %>
<% else %>
<main>
  <div class="container">
  <div class="row">
    <div class="col-lg-5 col-md-12　col-xs-12 mt-4 music-single">
    <%= attachment_image_tag @music, :image, format: 'png', class:"music-size"%>
    </div>
    <div class="col-lg-7 disco">
    <span style="font-family: 'Cormorant Garamond', serif;">MUSIC</span>
    <span><%= @music.category.name %></span>
    <span><%= @music.release %></span>
    <span><%= @music.title%></span>
    <span><%= @music.title%></span>
    <span><%= @music.price %></span>
    <a href="<%= @music.presave %>" class="btn-open" target="_blank"rel="noopener noreferrer">STREAMING</a>
    </div>
  </div>
  </div>
</main>
<% end %>
<%= javascript_include_tag 'aimsition.js' %>
<%= javascript_include_tag 'none.js' %>

app/views/news/index.html.erb
  <main>
  <div class="container">
    <div class="row">
        <div class="col-lg-2">
        <span class="index-title">NEWS</span>
        </div>
        <div class="col-lg-10">
            <div class="row">
                <% @news.each do |news| %>
          <div class="col-lg-4 col-md-6 col-xs-12 mb-3 news-mobile">
          <%= link_to news_path(news.id), data: {"turbolinks" => false} do %>
            <div class="card bg-light h-100" style="width: 15rem; margin: 0 auto;">
                  <%= attachment_image_tag news, :news_image,　format: 'png', fallback: "news.jpg", size: "237x237" %>
                <div class="card-body">
                  <p class="card-text"><%= news.title%></p>
                  <p class="card-text"><small class="text-muted"><%= news.created_at.strftime('%Y-%m-%d') %></small></p>
                </div>
            </div>
          <% end %>
          </div>
        <% end %>
            </div>
        </div>
    </div>
  </div>
  </main>
<%= javascript_include_tag 'aimsition.js' %>
<%= javascript_include_tag 'news.js' %>

app/views/news/new.html.erb
  <div class="container">
    <div class="row"> 
     <div class="col-12 mx-auto">
    <%= form_with model: @news, local: true do |f| %>
    
    <div class="field">
    <%= f.label "タイトル" %>
    <%= f.text_field :title, class:"form-control"%>
    </div>

   <div class="field">
    <%= f.label "内容" %>
    <%= f.text_area :body, class:"form-control" %>
   </div>

    <%= f.label "曲選択" %>
    <div class="category">
     <%= f.collection_select(:music_id, Music.all, :id, :title, prompt: "-- 選択してください--") %>
    </div>

   <div class="field">
    <%= f.label "画像"%>
    <%= f.attachment_field :news_image %>
   </div>
   
    <%= f.submit "作成", class:"btn btn-info"%>
    <% end %>
    <img id="preview">
    </div>
   </div>
  </div>
  <%= javascript_include_tag 'news.js' %>

app/views/news/show.html.erb
<main>
<div class="container">
  <div class="row" style=" margin-left: 0; margin-right: 0;">

   <div class="col-lg-12">
   <%= link_to news_index_path, data: {"turbolinks" => false} do %>
    <span class="news-info">NEWS</span>
  <% end %>
   </div>

    <div class="col-lg-6 news-image" style="padding-left: 0; padding-right: 0;">
    <%= attachment_image_tag @news, :news_image, class:"jk",　format: 'png', fallback: "news.jpg"%>
    </div>
   
    <div class="col-lg-6 news-title">
     <%= @news.title%>
     
    <div class="news-created">
     <%= @news.created_at.strftime('%Y-%m-%d') %>
    </div>

    <div class="news-body">
    <%= @news.body%>
    </div>

      <% if @news_music.present?%>
      <div class="news-link">
       <%= link_to("show-more", music_path(@news_music.music),{class:"btn-open animsition-link"}) %>
      </div>
      <% end %>

    </div>

   </div>
  </div>
</div>
</main>
<%= javascript_include_tag 'none.js' %>
<%= javascript_include_tag 'aimsition.js' %>