config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users, only:[:sign_in, :sign_out, :session]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#top"
  get "home/bio" => "homes#bio"
  resources :categories, param: :name, only:[:index, :create, :show]
  resources :musics do
    resources :music_choices, expect: [:new, :show]
    get '/previews' => 'music_choices#previews'
  end
   resources :news
   resources :top_musics, only:[:create, :destroy]
   get 'news/search' => 'news/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true
  has_many :musics
  
  def to_param
    name
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :category
  validates :image, presence: true
  attachment :image
  has_many :music_choices, dependent: :destroy
  has_many :news_musics, dependent: :destroy
  has_many :news, through: :news_musics
  has_many :top_musics, dependent: :destroy
end

app/models/music_choice.rb
class MusicChoice < ApplicationRecord
  validates :lyrics, presence: true
  validates :song_title, presence: true
  belongs_to :music
  attachment :background_image
end

app/models/news.rb
class News < ApplicationRecord
  attachment :news_image
  has_many :news_musics, dependent: :destroy
  has_many :musics, through: :news_musics
end

app/models/news_music.rb
class NewsMusic < ApplicationRecord
  belongs_to :news
  belongs_to :music
end

app/models/top_music.rb
class TopMusic < ApplicationRecord
  belongs_to :music
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @top_musics = TopMusic.order(updated_at: :desc).limit(1)
    @news = News.last(3)
  end

  def bio
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def new
    @music = Music.new
    @musics = Music.all
  end

  def create
    @music = Music.new(music_params)
    if @music.save
      redirect_to new_music_path
    else
      @musics = Music.all
      render :new
    end
  end

  def index
  @musics = Music.all
  @categories = Category.all
  end
  
  def show
    @music =Music.find(params[:id])
    @music_choice = MusicChoice.new
    @music_choices = @music.music_choices
  end
 
private

  def music_params
    params.require(:music).permit(:category_id, :image, :title, :price, :release, :presave)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
    @news= News.new
  end
  
  def create
    news = News.create(title: news_params[:title], body: news_params[:body], news_image: news_params[:news_image])
    
    if news_params[:music_id].present?
      music = Music.find_by(id: news_params[:music_id])
      NewsMusic.create(news_id: news.id, music_id: music.id)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def index
    @news = News.all.order(id: "DESC")
  end

  def show
    @news = News.find(params[:id])
    @news_music = NewsMusic.find_by(news_id: @news.id)
  end
  private
  def news_params
    params.require(:news).permit(:title, :body, :news_image, :music_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/music_choices_helper.rb
module MusicChoicesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/top_musics_helper.rb
module TopMusicsHelper
end

app/views/layouts/_header.html.erb
    <header class="header">
      <%= link_to root_path, "data-turbolinks" => "false" do%>
      <div class="header_logo"></div>
      <% end %>
    <nav class="desk-top_header">
          <% if user_signed_in? %>
              <%= link_to destroy_user_session_path, class:"bt cubic", method: :delete do %>
              <span class="hovering">ログアウト</span><span class="default">logout</span>
              <% end %>

              <%= link_to new_music_path,class:"bt cubic animsition-link" do %>
              <span class="hovering">曲作成</span><span class="default">Create</span>
              <% end %>

              <%= link_to contacts_path, class:"bt cubic animsition-link" do %>
              <span class="hovering">メール確認</span><span class="default">メール確認</span>
              <% end %>

              <%= link_to new_news_path, class:"bt cubic animsition-link" do %>
              <span class="hovering">News作成</span><span class="default">News</span>
              <% end %>

              <%= link_to categories_path, class:"bt cubic animsition-link" do %>
              <span class="hovering">カテゴリー作成</span><span class="default">カテゴリー作成</span>
              <% end %>
          <% else %>
          <%= link_to news_index_path, class:"bt cubic animsition-link", data: {"turbolinks" => false} do %>
              <span class="hovering">お報せ</span><span class="default">News</span>
          <% end %>

          <%= link_to musics_path, class:"bt cubic animsition-link", data: {"turbolinks" => false} do %>
            <span class="hovering">楽曲</span><span class="default">Music</span>
          <% end %>
          
          <%= link_to home_bio_path, class:"bt cubic animsition-link" do %>
              <span class="hovering">我々</span><span class="default">Biography</span>
          <% end %>

            <a href="#" class="bt cubic"><span class="hovering">coming soon</span><span class="default">Store</span></a>

              <%= link_to new_contact_path,class:"bt cubic animsition-link" do %>
              <span class="hovering">ご連絡</span><span class="default">Contact</span>
              <% end %>
          <% end %>
    </nav>
        <button class="mobile-menu-btn">
          <span></span>
          <span></span>
          <span></span>
        </button>
    </header>

app/views/layouts/_mobilenav.html.erb
<nav class="mobile-menu">
      <ul class="mobile-menu__main">
          <li class="mobile-menu__item">
          <%= link_to news_index_path, class:"mobile-menu__link animsition-link" do %>
                    <span class="mobile-title">News</span><span class="sub-title">お報せ</span>
          <% end %>
          </li>
          
          <li class="mobile-menu__item">
          <%= link_to musics_path, class:"animsition-link mobile-menu__link" do %>
                  <span class="mobile-title">Music</span><span class="sub-title">楽曲</span>
            <% end %>
          </li>

          <li class="mobile-menu__item">
          <%= link_to  home_bio_path, class:"mobile-menu__link animsition-link" do %>
                  <span class="mobile-title">Biography</span><span class="sub-title">我々</span>
          <% end %>
          </li>

          <li class="mobile-menu__item">
          <%= link_to root_path, class:"mobile-menu__link animsition-link" do %>
                  <span class="mobile-title">Store</span><span class="sub-title">coming soon</span>
          <% end %>
          </li>

           <li class="mobile-menu__item">
          <%= link_to new_contact_path, class:"mobile-menu__link animsition-link" do %>
                  <span class="mobile-title">Contact</span><span class="sub-title">ご連絡</span>
          <% end %>
          </li>
      </ul>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>buthoes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Benne&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&family=Noto+Serif+JP:wght@200;300;400;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&family=Playfair+Display&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <div class="animsition">
  <div id="butohes-log">
    <div id="butohes-log-image" class="cover-slide inview">
      <%= image_tag asset_path("butohes_logo_white.png", alt: "butohes.logo"), class:"logo" %><br>
    </div>
  </div>
  <div class="global-container">
      <%= render "layouts/header" %>
        <%= yield %>
      <footer>
      <div class="footer-visual">
      <p class="footer-text">©butohes</p>
      <a href="https://www.youtube.com/channel/UCSGWPh94G3eSPPEV6bnjJ6g"  target="_blank"rel="noopener noreferrer"><i class="fab fa-youtube"></i></a>
      <a href="https://www.instagram.com/butohesgram/"  target="_blank"rel="noopener noreferrer"><i class="fab fa-instagram"></i></a>
      <a href="https://butohes.bandcamp.com/releases"  target="_blank"rel="noopener noreferrer"><i class="fab fa-bandcamp"></i></a>
      <a href="https://soundcloud.com/butohes_japan/"  target="_blank"rel="noopener noreferrer"><i class="fab fa-soundcloud"></i></a>
      <a href="https://twitter.com/butohes_japan"  target="_blank"rel="noopener noreferrer"><i class="fab fa-twitter-square"></i></a>
      </div>
      </footer>
  </div>
  <%= render "layouts/mobilenav" %>
 </div>
      <% if user_signed_in?%>
      <style>
      header {
        width: 100%;
        height: 60px;
        background-color: black;
        display: flex;
        z-index: 1;
        top: 0;
        left: 0;
        position: relative;
      }
      .animsition{
        opacity: 1;
      }
      </style>
      <% end %>
</body>
  <%= javascript_include_tag 'mobile.js' %>
</html>